### ISSUE TITLE
Support for Catalan language

### ISSUE THREAD

**Issue by pmontp19** [jojost1/piholeremote-translations#118]
Hi! I would like to help to translate to Catalan "CA"

**Comment by jojost1** [comment]
Hi,
That's great! I'll duplicate the English files soon so you can add your translations :-) Thanks!

**Comment by jojost1** [comment]
@pmontp19 I've added the files! 😄 the files in the 'App' folder are most important by far, followed by the app description. Other files are nice to have :-)
