### ISSUE TITLE
Add a new language (German)

### ISSUE THREAD

**Issue by tigger30926** [jojost1/piholeremote-translations#35]
Hello,
I would like to assist you with the translation into German. 

Kind regards from Hannover (Germany)

**Comment by berndwa** [comment]
I would like to help too with a german translation.

**Comment by tigger30926** [comment]
ok, how do we want to start the translation?

**Comment by phil-lipp** [comment]
I think its: Create Issue for new language -> filles (de.*) get added in the code with english placeholders -> edit them and submit pull requests.
Since the german files de.* got already addead you can skip ahead and continue with step 3

**Comment by jojost1** [comment]
Hi! Yeah @phil-lipp is right, you can fork the repo and make PRs when you've completed (part of) the translations :-) I'll then merge them in & create new beta builds so they can be double checked. To join the beta please mail me using the Help & Feedback inside the app :-)

**Comment by phil-lipp** [comment]
> 
> 
> Hi guys. I started with translating the language file an I translated it up to line 42.
> 
> Kurze grundsätzliche Frage: Siezen oder Duzen wir den Anwender? Ich habe jetzt mit dem höflichen, großen "Du" gearbeitet...

Gute Frage. Ich würde grundsätzlich sagen, dass das keine hoch-offizielle Anwendung (wie z.B. eine Banking-App oder so) ist und daher auch das Sie eher Fehl am Platz ist.
Ich würde dem eine Frage hinzufügen: Soll alles einfach stumpf auf deutsch übersetzt werden? Was ist mit feststehenden Begriffen wie z.B. Whitelist? 
Ich finde, dass solche Begriffe auf englisch gelassen werden sollten, da Menschen, die ein PiHole haben, eh wissen (bzw. wissen müssen/sollten) was diese Begriffe bedeuten und im technischen Sprachgebrauch (auf deutsch) auch häufig verwendet werden.

**Comment by jojost1** [comment]
(Google Translate tried it's best for me)

I'd say keep it informal. For example for Dutch translations, I've sticked to 'Whitelist/Blacklist' as terms, as well as 'Query' / 'Home' / 'Query Log'.. Just sounds more natural to me. Depends a lot on the language as well I guess :-) 

If any translations end up 'feeling' strange or out of place, we can always change them!

**Comment by berndwa** [comment]
I'm totally with both of you! "Weißliste" is not so fine I think ;-)

**Comment by berndwa** [comment]
Please review my previous translations - _Home_, _Statistic_, _Query Log_ and most of _Settings_ should now work in german :)

**Comment by jojost1** [comment]
After a quick review it looks like:
- App: missing lines 86, 105, 183-267, 302-366, 392-439, 462-487, 500-543
- App: lines 76-77 are a wrong language
- Description: still todo
- Widgets: still todo
- SiriShortcuts: still todo
- ActionExtension: done

Any idea when you (/someone) would have time to finish them? When App & Description are ready I can release v2.11.2 😄 other files can come later if needed, they're less important anyways.

**Comment by berndwa** [comment]
I think I have translated most of the app. I'll take a look at the description tomorrow. 8-)

**Comment by jojost1** [comment]
German is included in v2.11.2 released on June 15th!
